apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: otelcol-kube
spec:
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http
  selector:
    name: loki
  type: ClusterIP
