apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: otelcol-kube
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      logging:
        loglevel: debug

    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [logging]