apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: otelcol-kube
spec:
  ports:
  - name: grpc
    port: 4317
    protocol: TCP
  - name: http
    port: 4318
    protocol: TCP
  selector:
    app: otel-collector